name: 'All Checks Passed'
description: 'Makes sure all other checks for a commit have passed'
author: 'Arup Group'
branding:
  icon: 'check-circle'
  color: 'green'
runs:
  using: 'node20'
  main: 'dist/index.js'
